SmartNews_unpackaged/objects/News__c.object
<CustomObject>
    <fields>
        <fullName>Author__c</fullName>
        <label>Author</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Content__c</fullName>
        <label>Content</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>SourceUrl__c</fullName>
        <label>SourceUrl</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Source__c</fullName>
        <label>Source</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Title__c</fullName>
        <label>Title</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>publishedAt__c</fullName>
        <label>Published at</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>urlToImage__c</fullName>
        <label>urlToImage</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <label>News</label>
    <nameField>
        <label>News</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SmartNews_unpackaged/objects/News_Source__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>business</fullName>
                </value>
                <value>
                    <fullName>entertainment</fullName>
                </value>
                <value>
                    <fullName>general</fullName>
                </value>
                <value>
                    <fullName>health</fullName>
                </value>
                <value>
                    <fullName>science</fullName>
                </value>
                <value>
                    <fullName>sports</fullName>
                </value>
                <value>
                    <fullName>technology</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ar</fullName>
                </value>
                <value>
                    <fullName>au</fullName>
                </value>
                <value>
                    <fullName>br</fullName>
                </value>
                <value>
                    <fullName>ca</fullName>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
                <value>
                    <fullName>es</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
                <value>
                    <fullName>gb</fullName>
                </value>
                <value>
                    <fullName>ie</fullName>
                </value>
                <value>
                    <fullName>in</fullName>
                </value>
                <value>
                    <fullName>is</fullName>
                </value>
                <value>
                    <fullName>it</fullName>
                </value>
                <value>
                    <fullName>nl</fullName>
                </value>
                <value>
                    <fullName>no</fullName>
                </value>
                <value>
                    <fullName>pk</fullName>
                </value>
                <value>
                    <fullName>ru</fullName>
                </value>
                <value>
                    <fullName>sa</fullName>
                </value>
                <value>
                    <fullName>se</fullName>
                </value>
                <value>
                    <fullName>us</fullName>
                </value>
                <value>
                    <fullName>za</fullName>
                </value>
                <value>
                    <fullName>zh</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>ID__c</fullName>
        <label>ID</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Language__c</fullName>
        <label>Language</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ar</fullName>
                </value>
                <value>
                    <fullName>de</fullName>
                </value>
                <value>
                    <fullName>en</fullName>
                </value>
                <value>
                    <fullName>es</fullName>
                </value>
                <value>
                    <fullName>fr</fullName>
                </value>
                <value>
                    <fullName>he</fullName>
                </value>
                <value>
                    <fullName>it</fullName>
                </value>
                <value>
                    <fullName>nl</fullName>
                </value>
                <value>
                    <fullName>no</fullName>
                </value>
                <value>
                    <fullName>pt</fullName>
                </value>
                <value>
                    <fullName>ru</fullName>
                </value>
                <value>
                    <fullName>se</fullName>
                </value>
                <value>
                    <fullName>ud</fullName>
                </value>
                <value>
                    <fullName>zh</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ABC News</fullName>
                </value>
                <value>
                    <fullName>ABC News (AU)</fullName>
                </value>
                <value>
                    <fullName>ANSA.it</fullName>
                </value>
                <value>
                    <fullName>Aftenposten</fullName>
                </value>
                <value>
                    <fullName>Al Jazeera English</fullName>
                </value>
                <value>
                    <fullName>Argaam</fullName>
                </value>
                <value>
                    <fullName>Ars Technica</fullName>
                </value>
                <value>
                    <fullName>Ary News</fullName>
                </value>
                <value>
                    <fullName>Associated Press</fullName>
                </value>
                <value>
                    <fullName>Australian Financial Review</fullName>
                </value>
                <value>
                    <fullName>Axios</fullName>
                </value>
                <value>
                    <fullName>BBC News</fullName>
                </value>
                <value>
                    <fullName>BBC Sport</fullName>
                </value>
                <value>
                    <fullName>Bild</fullName>
                </value>
                <value>
                    <fullName>Blasting News (BR)</fullName>
                </value>
                <value>
                    <fullName>Bleacher Report</fullName>
                </value>
                <value>
                    <fullName>Bloomberg</fullName>
                </value>
                <value>
                    <fullName>Breitbart News</fullName>
                </value>
                <value>
                    <fullName>Business Insider</fullName>
                </value>
                <value>
                    <fullName>Business Insider (UK)</fullName>
                </value>
                <value>
                    <fullName>Buzzfeed</fullName>
                </value>
                <value>
                    <fullName>CBC News</fullName>
                </value>
                <value>
                    <fullName>CBS News</fullName>
                </value>
                <value>
                    <fullName>CNBC</fullName>
                </value>
                <value>
                    <fullName>CNN</fullName>
                </value>
                <value>
                    <fullName>CNN Spanish</fullName>
                </value>
                <value>
                    <fullName>Crypto Coins News</fullName>
                </value>
                <value>
                    <fullName>Daily Mail</fullName>
                </value>
                <value>
                    <fullName>Der Tagesspiegel</fullName>
                </value>
                <value>
                    <fullName>Die Zeit</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <label>News_Source</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>News_Sources</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SmartNews_unpackaged/classes/SmartNewsController.cls
public class SmartNewsController {
	@AuraEnabled
    public static List<News__c> parseJSONResponse() {  
        System.debug('Inside SmartNewsController');
        List<News__c> listOfNews;
        HttpRequest request;
        HttpResponse response;
        JSONParserUtil parseToApex;
        try{
			Http httpProtocol = new Http();
        
            // Create HTTP request to send.
            request = new HttpRequest();
            // Set the endpoint URL.
            String endpoint = 'https://newsapi.org/v2/top-headlines?' +'category=technology&' + 'country=us&' + 'source=abc-news&' + 'apiKey=3c533185a10a4307a47c1356d4d7b9be';
            request.setEndPoint(endpoint);
            // Set the HTTP verb to GET.
            request.setMethod('GET');
            request.setTimeout(60000); 
            // Send the HTTP request and get the response.
            // The response is in JSON format.
            response = httpProtocol.send(request);
            System.debug(response.getBody());
            String jsonString = response.getBody();
            parseToApex = JSONParserUtil.parse(jsonString);
            
            endpoint = 'https://newsapi.org/v2/sources?apiKey=3c533185a10a4307a47c1356d4d7b9be';
            request.setEndPoint(endpoint);
            // Set the HTTP verb to GET.
            request.setMethod('GET');
            request.setTimeout(60000); 
            // Send the HTTP request and get the response.
            // The response is in JSON format.
            response = httpProtocol.send(request);
            System.debug(response.getBody());            
        }catch(System.CalloutException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        }
        
        String jsonSourceString = response.getBody();
        JSON2ApexSources parseToApexSources = JSON2ApexSources.parse(jsonSourceString);
		
        Boolean isSavedNews = saveRecords(parseToApex);
        System.debug(parseToApex);
        System.debug(isSavedNews);
        listOfNews = [select id, publishedAt__c, SourceUrl__c, Author__c, Title__c, Description__c, urlToImage__c, Source__c,
                                       Content__c from News__c order by publishedAt__c desc];
									   
		Boolean isSavedSources = saveSources(parseToApexSources);
        System.debug(parseToApexSources);
        System.debug(isSavedSources);
       
        return listOfNews;
    }   
    
    public static Boolean saveRecords(JSONParserUtil parseToApex) { 
        Boolean isSaved = false;
        if(parseToApex.status.equalsignorecase('ok')){
            List<News__c> listOfNews = new List<News__c>();
            News__c newsRecord;
            Boolean newRecordsLoaded = true;
            
            //remove old records from the object
            List<News__c> oldRecordList = [select id, publishedAt__c, SourceUrl__c from News__c order by publishedAt__c desc];
            
            if(oldRecordList != null && oldRecordList.size() > 0){
                News__c oldRecord = oldRecordList[0];
                Date lastRecordSavedDate = date.newinstance(oldRecord.publishedAt__c.year(), oldRecord.publishedAt__c.month(), 
                                                        oldRecord.publishedAt__c.day());
            
                if(lastRecordSavedDate != System.today()){
                    delete [select id from News__c];
                }else{
                    for(JSONParserUtil.Articles article : parseToApex.articles){
                        if(article.url.equalsignorecase(oldRecord.SourceUrl__c)){
                            newRecordsLoaded = false;
                            break;
                        }
                    }
                }
            }
            
            
            if(newRecordsLoaded){
                 for(JSONParserUtil.Articles article : parseToApex.articles){
                    newsRecord = new News__c();
                    newsRecord.Author__c = article.author;
                    newsRecord.Title__c = article.title;
                    newsRecord.Description__c = article.description;
                    newsRecord.SourceUrl__c = article.url;
                    newsRecord.urlToImage__c = article.urlToImage;
                    newsRecord.publishedAt__c =  (DateTime)json.deserialize(article.publishedAt, datetime.class);
                    newsRecord.Content__c = article.content;
                    newsRecord.Source__c = String.valueOf(article.source);
                    listOfNews.add(newsRecord);
                }
                if( listOfNews != null && listOfNews.size() > 0 ){
                    insert listOfNews;
                    isSaved = true;
                }
            }
        }
        
        return isSaved;
    }
    
       
    public static Boolean saveSources(JSON2ApexSources parseToApex) { 
        Boolean isSaved = false;
        if(parseToApex.status.equalsignorecase('ok')){
            System.debug('Status:'+parseToApex.status);
			List<News_Source__c> listOfNewsSources = new List<News_Source__c>();
            News_Source__c newsSouceRecord;
            
            //remove old records from the object
            List<News_Source__c> oldRecordList = [select id from News_Source__c];
            
            if(oldRecordList != null){
                delete oldRecordList;
            }
            
            for(JSON2ApexSources.Sources source : parseToApex.Sources){
                    newsSouceRecord = new News_Source__c();
                    newsSouceRecord.ID__c = source.id;
                    newsSouceRecord.Name__c = source.name;
                	newsSouceRecord.Name = source.name;
                    newsSouceRecord.Description__c = source.description;
                    newsSouceRecord.URL__c = source.url;
                    newsSouceRecord.Category__c = source.category;
                    newsSouceRecord.Language__c = source.language;
                	newsSouceRecord.Country__c = source.country;
                    listOfNewsSources.add(newsSouceRecord);
                }
            
            if(listOfNewsSources != null && listOfNewsSources.size() > 0){
                insert listOfNewsSources;
                isSaved = true;
            }
            System.debug('listOfNewsSources:'+ listOfNewsSources);
        }
        System.debug('Sources Saved:'+ isSaved);
        
        return isSaved;
    }
    
     @AuraEnabled
     public static List <String> getselectOptions(sObject objObject, string fieldName) {
      system.debug('objObject --->' + objObject);
      system.debug('fieldName --->' + fieldName);
      List < String > allOpts = new list < String > ();
      // Get the object type of the SObject.
      Schema.sObjectType objType = objObject.getSObjectType();
     
      // Describe the SObject using its object type.
      Schema.DescribeSObjectResult objDescribe = objType.getDescribe();
     
      // Get a map of fields for the SObject
      map < String, Schema.SObjectField > fieldMap = objDescribe.fields.getMap();
      system.debug('fieldMap ---->' + fieldMap);
     
      // Get the list of picklist values for this field.
      list < Schema.PicklistEntry > values =
      fieldMap.get(fieldName).getDescribe().getPickListValues();
     
      // Add these values to the selectoption list.
      for (Schema.PicklistEntry a: values) {
       allOpts.add(a.getValue());
      }
      system.debug('allOpts ---->' + allOpts);
      allOpts.sort();
      return allOpts;
     }
}